
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdzilehnqgmiixfcgfxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkemlsZWhucWdtaWl4ZmNnZnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDk3NTcsImV4cCI6MjA2MDE4NTc1N30.tUSwOQ9HrdNaCv6ps0YAFUx6k1YKMxBKGf75bBkke-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
