name: Send Career-Track Request

on:
  schedule:
    # Every Monday and Friday at 09:00 UTC
    - cron: "0 9 * * 1,5"
  workflow_dispatch:    # lets you run it manually

jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Replay Supabase request
        run: |
          curl --path-as-is -i -s -k -X 'POST' \
            -H 'Host: jdzilehnqgmiixfcgfxc.supabase.co' \
            -H 'Sec-Ch-Ua-Platform: "macOS"' \
            -H "Authorization: Bearer ${{ secrets.CT_BEARER }}" \
            -H 'X-Supabase-Api-Version: 2024-01-01' \
            -H 'Accept-Language: en-US,en;q=0.9' \
            -H 'Sec-Ch-Ua: "Not.A/Brand";v="99", "Chromium";v="136"' \
            -H 'Sec-Ch-Ua-Mobile: ?0' \
            -H 'X-Client-Info: supabase-js-web/2.49.4' \
            -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36' \
            -H 'Content-Type: application/json;charset=UTF-8' \
            -H "Apikey: ${{ secrets.CT_APIKEY }}" \
            -H 'Accept: */*' \
            -H 'Origin: https://career-track-board.lovable.app' \
            -H 'Sec-Fetch-Site: cross-site' \
            -H 'Sec-Fetch-Mode: cors' \
            -H 'Sec-Fetch-Dest: empty' \
            -H 'Referer: https://career-track-board.lovable.app/' \
            -H 'Accept-Encoding: gzip, deflate, br' \
            -H 'Priority: u=1, i' \
            --data-binary '{"email":"${{ secrets.CT_EMAIL }}","password":"${{ secrets.CT_PASS }}","gotrue_meta_security":{}}' \
            'https://jdzilehnqgmiixfcgfxc.supabase.co/auth/v1/token?grant_type=password'
